package:
  name: bootupd
  version: 0.2.31
  epoch: 0
  description: Bootloader updater
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/coreos/bootupd.git
      tag: v${{package.version}}
      expected-commit: de779db5376f692b314a0b447d700db5b42cc6b1

  - uses: patch
    with:
      patches: systemd-boot.patch

  - uses: cargo/build
    with:
      output: bootupd
      opts: |
        --release \
        --features systemd-boot

  - uses: autoconf/make-install

  - uses: strip

test:
  pipeline:
    - runs: |
        set -o pipefail
        bootupd --help | grep -F -e "Bootupd backend commands"
        bootupd --version | grep -F -e "${{package.version}}"
        bootupctl --help | grep -F -e "Bootupd client application"
        bootupctl --version | grep -F -e "${{package.version}}"

update:
  enabled: true
  github:
    identifier: coreos/bootupd
    strip-prefix: v
